version: '2.0'
services:
  persister:
    image: openjdk:8-jdk
    volumes:
      - ${PROJECTS_DIRECTORY}/persister:/persister
    working_dir: /persister
    command: ./gradlew bootRun
    ports:
      - 8080:8080

  mongo:
    image: tutum/mongodb
    environment:
      MONGODB_DATABASE: "${MONGO_DATABASE}"
      MONGODB_USER: "${MONGO_USER}"
      MONGODB_PASS: "${MONGO_PASS}"
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata: